name: Continuous Integration
on: push
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:latest
            ports:
              - 5432:5432
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: mysecretpassword
              POSTGRES_DB: testdb
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Set up PostgreSQL
        run: |
          psql -h localhost -U postgres -p 5432 -c "CREATE DATABASE testdb"
      

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...

      - name: Run tests
        run: |
          go test ./...
